# Kontrollime kas eelnevalt paigaldatud tarkvara on masinates, kui pole siis raporteerib ning paigaldab
- name: Kontrollime, raporteerime puuduvast ja paigaldame puuduva
  hosts: all
  become: true
  tasks:
    - name: debian servude check n deploy
      when: ansible_distribution in ["Debian", "Ubuntu"]
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - snmpd
        - tmux
        - mc
        - wget
        - tree
        - git
      notify:
        - Teavita puuduvatest paketidest

    - name: Dockeri paigaldus vajalikus hostis
      when: inventory_hostname == "HeiKi-DocKerHost" and ansible_distribution == "Debian"
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      notify:
        - Teavita puuduvatest paketidest

    - name: Paigalda CentOS-süsteemides vajalikud paketid
      when: ansible_distribution == "CentOS"
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - net-snmp
        - net-snmp-utils
        - tmux
        - mc
        - wget
        - tree
        - git
      notify:
        - Teavita puuduvatest paketidest

    - name: Paigalda openSUSE süsteemides vajalik tarkvara
      when: ansible_distribution == "openSUSE"
      zypper:
        name: "{{ item }}"
        state: present
      loop:
        - tmux
        - mc
        - wget
        - tree
        - git
        - net-snmp
      notify:
        - Teavita puuduvatest paketidest

  handlers:
    - name: Teavita puuduvatest paketidest
      debug:
        msg: "Paigaldatud puuduv tarkvara masinale {{ inventory_hostname }}"
