- name: Süsteemi uuendus
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes

- name: Paigalda Docker ja Compose
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Loo töökaust
  ansible.builtin.file:
    path: /opt/graylog
    state: directory

- name: Laadi docker-compose.yml
  ansible.builtin.copy:
    dest: /opt/graylog/docker-compose.yml
    content: |
      version: '3'
      services:
        mongodb:
          image: mongo:4.2
          restart: always
          volumes:
            - mongo_data:/data/db
        elasticsearch:
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
          environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
          ulimits:
            memlock:
              soft: -1
              hard: -1
          mem_limit: 1g
          restart: always
          volumes:
            - es_data:/usr/share/elasticsearch/data
        graylog:
          image: graylog/graylog:5.2
          environment:
            - GRAYLOG_PASSWORD_SECRET=nu11i5tTug3V@x2025
            - GRAYLOG_ROOT_PASSWORD_SHA2=a6144d2ab56981fb85d8140dbe84160625698a353861e03fa4aefd22e6333e32
            - GRAYLOG_HTTP_EXTERNAL_URI=http://10.0.91.52:9000/
            - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
          depends_on:
            - mongodb
            - elasticsearch
          ports:
            - "9000:9000"
            - "1514:1514/udp"
            - "12201:12201/udp"
          restart: always
          volumes:
            - graylog_data:/usr/share/graylog/data
      volumes:
        mongo_data:
        es_data:
        graylog_data:

- name: Käivita Graylog Docker Compose
  ansible.builtin.shell: |
    cd /opt/graylog && docker compose up -d
  args:
    creates: /opt/graylog/graylog_compose_initialized

- name: Luba vajalikud pordid tulemüüris
  ansible.builtin.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop:
    - '9000'
  ignore_errors: yes

- name: Luba UDP pordid tulemüüris
  ansible.builtin.ufw:
    rule: allow
    port: '{{ item }}'
    proto: udp
  loop:
    - '1514'
    - '12201'
  ignore_errors: yes
