---
- name: SSL sertifikaadi loomine ja Apache HTTPS seadistamine
  hosts: webserver
  become: yes

  vars:
    fqdn: kasutajatugi.oige.local
    ssl_dir: /etc/httpd/ssl

  tasks:
    - name: Loo SSL kataloog kui see ei eksisteeri
      file:
        path: "{{ ssl_dir }}"
        state: directory
        mode: '0755'

    - name: Loo privaatvõti
      command: openssl genrsa -out {{ ssl_dir }}/{{ fqdn }}.key 2048
      args:
        creates: "{{ ssl_dir }}/{{ fqdn }}.key"

    - name: Loo self-signed sertifikaat
      command: >
        openssl req -new -x509 -key {{ ssl_dir }}/{{ fqdn }}.key
        -out {{ ssl_dir }}/{{ fqdn }}.crt
        -days 365
        -subj "/CN={{ fqdn }}"
      args:
        creates: "{{ ssl_dir }}/{{ fqdn }}.crt"

    - name: Loo Apache SSL konfi fail
      copy:
        dest: /etc/httpd/conf.d/ssl_custom.conf
        content: |
          <VirtualHost *:443>
              ServerName {{ fqdn }}

              DocumentRoot /var/www/html

              SSLEngine on
              SSLCertificateFile {{ ssl_dir }}/{{ fqdn }}.crt
              SSLCertificateKeyFile {{ ssl_dir }}/{{ fqdn }}.key

              <Directory /var/www/html>
                  Options -Indexes +FollowSymLinks
                  AllowOverride All
              </Directory>

              ErrorLog logs/ssl_error_log
              CustomLog logs/ssl_access_log combined
          </VirtualHost>

    - name: Luba firewalld HTTPS (vajadusel)
      firewalld:
        service: https
        permanent: true
        state: enabled
        immediate: true
      ignore_errors: yes

    - name: Taaskäivita Apache
      systemd:
        name: httpd
        state: restarted
